/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Insets;
import javax.swing.*;
import javax.swing.text.*;

/**
 *
 * @author Juan Martin Dominguez M
 */
public class VentanaValidError extends javax.swing.JFrame implements java.beans.Customizer {
    
    private Object bean;
    
    public VentanaValidError(String mensajeEnviado){
        initComponents();
        // Escribir el texto recibido
        jTextAreaMnsjNoValido.setText(mensajeEnviado);
        jTextAreaMnsjNoValido.setLineWrap(true);
        jTextAreaMnsjNoValido.setWrapStyleWord(true);
        jTextAreaMnsjNoValido.setEditable(false);
    }

    //jLabelMnsjNoValido.setText(mensajeEnviado);
    /**
     * Creates new customizer VentanaValidError
     */
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextAreaMnsjNoValido = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jPanelEspacio = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(360, 270));
        setMinimumSize(new java.awt.Dimension(360, 270));
        setSize(new java.awt.Dimension(360, 270));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulo.setBackground(new java.awt.Color(0, 153, 51));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("¡Datos no válidos!");
        jPanelTitulo.add(jLabelTitulo);

        getContentPane().add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaMnsjNoValido.setEditable(false);
        jTextAreaMnsjNoValido.setColumns(20);
        jTextAreaMnsjNoValido.setLineWrap(true);
        jTextAreaMnsjNoValido.setRows(5);
        jTextAreaMnsjNoValido.setAlignmentX(0.0F);
        jTextAreaMnsjNoValido.setBorder(null);
        jTextAreaMnsjNoValido.setMaximumSize(new java.awt.Dimension(250, 125));
        jTextAreaMnsjNoValido.setMinimumSize(new java.awt.Dimension(250, 125));
        jTextAreaMnsjNoValido.setPreferredSize(new java.awt.Dimension(250, 125));
        jPanel1.add(jTextAreaMnsjNoValido);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 360, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAceptar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAceptar);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 360, 40));

        jPanelEspacio.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanelEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEspacio;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextArea jTextAreaMnsjNoValido;
    // End of variables declaration//GEN-END:variables
}
